#!/bin/bash -e

source ~/miniconda3/etc/profile.d/conda.sh

(
echo '**** activating mypy'
conda activate mypy
echo '**** activated mypy'

echo '**** running mypy'
mypy --py2 \
    pdart/archive \
    pdart/astroquery \
    pdart/fs \
    pdart/new_db \
    pdart/pds4 \
    pdart/rules \
    pdart/xml \
    AstroqueryDownload.py \
    BulkDownload.py \
    MakeNewArchive.py \
    TestMast.py \
    ValidateLabel.py
)