#!/bin/bash

die(){
    echo $@ >&2
}

usage(){
    die Usage: "$(basename $0)" '<apt-file>'
}

if [ $# -ne 1 ]; then
    usage
fi

APT_FILE=$1
shift

TEMP_DIR=$(mktemp -d "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
trap "rm -rf $TEMP_DIR" EXIT

TEMP_FILE1=$TEMP_DIR/$(basename $APT_FILE).utf8
TEMP_FILE2=$TEMP_DIR/$(basename $APT_FILE).pretty

xsltproc xml/convert-to-utf8.xslt $APT_FILE > $TEMP_FILE1
if [[ $? -ne 0 ]]; then
    die xsltproc failed
    exit 1
fi


xmllint --format --output $TEMP_FILE2 $TEMP_FILE1
if [[ $? -ne 0 ]]; then
    die xmllint failed
    exit 1
fi

mv $TEMP_FILE2 $APT_FILE
if [[ $? -ne 0 ]]; then
    die mv failed
    exit 1
fi

exit 0
