#! /bin/bash

# This script builds API documentation (similar to JavaDocs).  It also
# automatically opens the main index page.
source activate pdart

rm -rf apidocs
sphinx-apidoc -A 'The PDART Team' -V '0.0.1' -F -e -o apidocs ../pdart
sed -i .bck -e "s/'\.'/'\.\.'/" apidocs/conf.py
sed -i .bck -e "s/#sys.path/sys.path/" apidocs/conf.py
cd apidocs && make html && open _build/html/index.html

