#! /usr/bin/python
"""SCRIPT: generate the boilerplate for templates for XML elements in
PDS4 labels"""
import string
import sys

field = sys.argv[1]
lower = field.lower()

print """##############################

_{lower}_template = interpret_template(
    {q3}<{field}>
</{field}>{q3})
# type: NodeBuilderTemplate


def make_{lower}():
    # type: () -> NodeBuilder
    return _{lower}_template({{
            }})
""".format(q3='"""', lower=lower, field=field)

