#!/bin/bash
set -eu

# A temporary script to restore downloaded files to their original
# state from tarballs.  Used while developing the pipeline to handle
# changed files.

rm -rf tmp-working-dir/hst_09059/documentDownload || exit 0
open -W tmp-working-dir/hst_09059/documentDownload.tar.gz 
rm -rf tmp-working-dir/hst_09059/mastDownload || exit 0
open -W tmp-working-dir/hst_09059/mastDownload.tar.gz