#!/bin/bash -e

source activate mypy
mypy --silent-imports --py2 \
    pdart/browse \
    pdart/db \
    pdart/fs \
    pdart/hst \
    pdart/pds4 \
    pdart/pds4labels \
    pdart/reductions \
    pdart/rules \
    pdart/tasks \
    pdart/xml \
    CheckBadFitsFiles.py \
    CheckKeywords.py \
    CheckSuffixes.py \
    CheckTimes.py \
    CompleteArchive.py \
    DeleteBrowse.py \
    DeleteDB.py \
    DeleteDocs.py \
    Dev.py \
    MakeBundleDBs.py \
    MakeDB.py \
    MakeDocCollections.py \
    MakeDocLabel.py \
    MakeLabel.py \
    MakeLabels.py \
    MakeRawBrowse.py \
    SearchDev.py \
    SqlAlch.py \
    SqlAlchComplete.py \
    TestHstParams.py \
    TestMast.py \
    ValidateArchive.py \
    ValidateLabel.py \
    ValidateLabels.py
