#!/bin/bash -e

# You must have Miniconda for Python 2.7 installed, probably from
# http://conda.pydata.org/miniconda.html

# Uncomment the following line back in if you want to rebuild the
# environment from scratch.

conda update -y conda

### conda remove -y --name pdart --all

# Create a minimal environment and activate it.  
conda create -y --name pdart mock pil pip psutil pyparsing \
    pytest sphinx sqlalchemy

source activate pdart

# for debugging
conda install -y -c asmeurer pudb=2015.3

# We install pyfits *before* scipy because it uses an earlier version
# of numpy.  It doesn't complain if its numpy is upgraded; scipy
# *does* complain if its version of numpy is downgraded.

conda install -y -c stsci pyfits=v3.3.0.git
conda install -y scipy

conda install -y -c astropy astroquery

# This is used only for mypy.
conda install -y -c bioconda typing

# This is used only by pdart.reductions.DbCReduction.  It may be
# removed in the future.
pip install PyContracts

# Install PyFilesystem.
pip install fs

# Run our basic operations (checking for formatting, unit-testing, and
# building docs) to see if the environment is working.
./pep8 && ./test && ./build-api-docs

echo
echo "Run 'source activate pdart' to activate the environment."
