#!/bin/bash -ex

# You must have Miniconda for Python 2.7 installed, probably from
# http://conda.pydata.org/miniconda.html

### conda update conda

# Uncomment the following line back in if you want to rebuild the
# environment from scratch.

(conda remove -y --name pdart --all) || echo "no pdart environment to remove"

# Create a minimal environment and activate it.  
conda create -y --name pdart mock psutil pycodestyle pyparsing \
    pytest sphinx sqlalchemy python=2.7

source activate pdart

### conda install -c anaconda pil

# for debugging
conda install -c asmeurer pudb=2015.3

# We install pyfits *before* scipy because it uses an earlier version
# of numpy.  It doesn't complain if its numpy is upgraded; scipy
# *does* complain if its version of numpy is downgraded.

conda install -c stsci pyfits=v3.3.0.git
conda install scipy

conda install -c astropy astroquery

# This is used only for mypy.
conda install -c bioconda typing

# This is used only by pdart.reductions.DbCReduction.  It may be
# removed in the future.
pip install PyContracts

# Install PyFilesystem.
pip install fs

# Check for pds-tools.
if [ ! -d "$HOME/pds-tools" ]; then
    echo
    echo "You do not have a copy of pds-tools in your home directory."
    echo -n "Download from github? [y/n] "
    read answer
    if [ $answer == "y" ]; then
        git clone "https://github.com/SETI/pds-tools.git" "$HOME/pds-tools"
    else
        echo "No?  Then hack add_pds_tools.py to point to it."
        exit 1
    fi
fi

# Run our basic operations (checking for formatting, unit-testing, and
# building docs) to see if the environment is working.
./pep8 && ./test && ./build-api-docs

echo
echo "Run 'source activate pdart' to activate the environment."
