#!/bin/bash
echo Running unit tests:
echo '-- FileArchive'
python FileArchive.py
echo '-- Heuristic'
python Heuristic.py
echo '-- HstFilename'
python HstFilename.py
echo '-- IdTables2'
python IdTables2.py
echo '-- LID'
python LID.py
echo '-- LIDVID'
python LIDVID.py
echo '-- Product'
python Product.py
echo '-- VID'
python VID.py
echo '-- XmlSchema'
python XmlSchema.py
echo starting archive validation at `date "+%Y-%m-%d %H:%M"`
python ValidateArchive.py
echo finished archive validation at `date "+%Y-%m-%d %H:%M"`

