#!/bin/bash
echo Running unit tests:
echo '-- FileArchive'
python FileArchive.py
echo '-- HstFilename'
python HstFilename.py
echo '-- Label'
python Label.py
echo '-- LID'
python LID.py
echo '-- LIDVID'
python LIDVID.py
echo '-- VID'
python VID.py
today=`date +%Y-%m-%d`
filename=archive-validation-$today.txt
python ValidateArchive.py | tee $filename

