class Node:
    def getElementsByTagName(self, tag_name: str): ...
    def toxml(self) -> str: ...

class Document:
    def createTextNode(self, txt: str): ...
    documentElement: Node
    def toxml(self) -> str: ...

class Text:
    pass

def parse(filename: str): ...
def parseString(txt: bytes): ...
