from typing import Any, List

class Node:
    def appendChild(self, child: Node) -> Node: ...
    childNodes: List[Node]
    def getAttribute(self, name: str) -> Any: ...
    def setAttribute(self, name: str, value: Any) -> None: ...
    def getElementsByTagName(self, tag_name: str) -> List[Node]: ...
    def normalize(self) -> None: ...
    def toxml(self) -> str: ...

class Text(Node):
    data: str

class Document(Node):
    def createElement(self, name: str) -> Node: ...
    def createProcessingInstruction(self, target: str, data: str) -> Node: ...
    def createTextNode(self, txt: str) -> Node: ...
    documentElement: Node
    def toxml(self) -> str: ...

def parse(filename: str) -> Document: ...
def parseString(txt: bytes) -> Document: ...
