from typing import Any

class Node:
    def toxml(self): ...
    def getElementsByTagName(self, tag_name: str): ...

class Document:
    def createTextNode(self, txt: str): ...
    documentElement: Node
    def toxml(self): ...

class Text:
    pass

def parse(filename: str): ...
def parseString(txt: bytes): ...
